apiVersion: apps/v1
kind: Deployment
metadata:
  name: product
  namespace: jenkins-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
        - name: product
          image: jinyoung/12st-product:${BUILD_NUMBER}
          ports:
            - containerPort: 8080
